### ISSUE TITLE
Node.js 18.x.x not support

### ISSUE THREAD

**Issue by officialkidmax** [vivmagarwal/strapi-plugin-custom-api-builder#15]
error strapi-plugin-custom-api@1.0.4: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.12.1"

**Comment by cedric-beurtheret-jcd** [comment]
Same issue for me:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-plugin-custom-api@1.0.4',
npm WARN EBADENGINE   required: { node: '>=12.x.x <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.6.1' }
npm WARN EBADENGINE }

**Comment by vivmagarwal** [comment]
Fixed.

**Comment by lionel-addvanto** [comment]
hmm, the error still persists for me

**Comment by fgrx** [comment]
The error still persists for me too

**Comment by akanshSirohi** [comment]
@vivmagarwal Issue is still there
![image](https://github.com/vivmagarwal/strapi-plugin-custom-api-builder/assets/34837239/7c1320d0-fe27-4ccf-878e-cfd00f0b8acd)

**Comment by titoworlddev** [comment]
I also have the error. I have node version 20.9.0 lts.

**Comment by tboulogne** [comment]
Use node 18.14.1 and i also have the error.
